modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="respawnhost_integration"
version="1.0.0"
displayName="RespawnHost Integration Menu"
authors="RespawnHost"
description='''Order and configure RespawnHost servers directly from the multiplayer menu.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.respawnhost_integration]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.respawnhost_integration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="CLIENT"
