plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'java'
}

version = project.findProperty("mod_version") ?: System.getenv("MOD_VERSION") ?: "1.0.0"
group = 'com.respawnhost'

base {
    archivesName = 'respawnhost_integration-1.14.4-fabric'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation("com.respawnhost:respawnhost-core:1.0.0") { transitive = false }
    include("com.respawnhost:respawnhost-core:1.0.0") { transitive = false }
}

processResources {
    def replaceProperties = [version: project.version]
    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(8)
}

java {
    withSourcesJar()
}
