modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="respawnhost_integration"
version="${mod_version}"
displayName="RespawnHost Integration Menu"
authors="RespawnHost"
description='''Order and configure RespawnHost servers directly from the multiplayer menu.'''

[[dependencies.respawnhost_integration]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="CLIENT"

[[dependencies.respawnhost_integration]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="CLIENT"
