modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "respawnhost_integration"
version = "${version}"
displayName = "RespawnHost Integration Menu"
description = "Order and configure RespawnHost servers directly from the multiplayer menu."
authors = "RespawnHost"
displayURL = "https://respawnhost.com"

[[dependencies.respawnhost_integration]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.respawnhost_integration]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,26.1)"
ordering = "NONE"
side = "CLIENT"

