buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

plugins {
    id 'eclipse'
    id 'java'
}
apply plugin: 'net.minecraftforge.gradle'

version = project.findProperty("mod_version") ?: System.getenv("MOD_VERSION") ?: "1.0.0"
group = 'com.respawnhost'
archivesBaseName = 'respawnhost-integration-1.18.2-forge'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.18.2'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                respawnhost_integration {
                    source sourceSets.main
                }
            }
        }
    }
}

configurations {
    coreBundle
    implementation.extendsFrom coreBundle
}

repositories {
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.18.2-40.2.21'
    coreBundle('com.respawnhost:respawnhost-core:1.0.0') { transitive = false }
}

jar {
    from({
        configurations.coreBundle.collect { it.isDirectory() ? it : zipTree(it) }
    }) {
        exclude 'META-INF/**'
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    manifest {
        attributes([
                "Specification-Title"   : "respawnhost_integration",
                "Specification-Vendor"  : "RespawnHost",
                "Specification-Version" : "1",
                "Implementation-Title"  : project.name,
                "Implementation-Version": project.jar.archiveVersion,
                "Implementation-Vendor" : "RespawnHost"
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
