modLoader = "javafml"
loaderVersion = "[3,)"
license = "MIT"

[[mods]]
modId = "respawnhost_integration"
version = "${version}"
displayName = "RespawnHost Integration Menu"
description = "Order and configure RespawnHost servers directly from the multiplayer menu."
authors = "RespawnHost"
displayURL = "https://respawnhost.com"

[[dependencies.respawnhost_integration]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.respawnhost_integration]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,1.21)"
ordering = "NONE"
side = "CLIENT"
