org.gradle.jvmargs=-Xmx3G
org.gradle.java.installations.paths=C:/Program Files/BellSoft/LibericaJDK-26-Full

minecraft_version=26.1.2
loader_version=0.19.3
fabric_version=0.155.2+26.1.2

mod_version=1.0.0
maven_group=com.respawnhost.integration
archives_base_name=respawnhost-integration-26.1-fabric
